server:
  port: 8080

spring:
  application:
    name: advanced-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/gateway
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.data.mongodb: INFO