server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false  # Updated property
          routes: []  # Updated property
          filter:
            path-rewrite:
              enabled: true
            circuit-breaker:
              enabled: true
            redis-rate-limiter:
              enabled: true
            timeout:
              enabled: true
            retry:
              enabled: true
            request-rate-limiter:
              enabled: true
      default-filters:
        - name: Resilience4J
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api_gateway
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.gateway: DEBUG
    reactor.netty: INFO
    com.netflix.discovery: OFF
    com.netflix.eureka: OFF

management:
  endpoints:
    web:
      exposure:
        include: gateway, gateway-refresh, health, info

metrics:
  collection:
    enabled: true
    retention-days: 30
  analysis:
    enabled: true
    schedule: "0 0/15 * * * *"