server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: api_gateway
      auto-index-creation: true

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.gateway: DEBUG